### ISSUE TITLE
Remove Excluded architectures flag

### ISSUE THREAD

**Issue by DagAgren** [Adyen/adyen-3ds2-ios#20]
Is there any chance of getting the framework correctly built for both x86_64 and arm64 on simulator? The EXCLUDED_ARCHS flag added to the podspec causes various problems when developing on M1, and is preventing various testing and build system improvements we want to make in our project.

**Comment by mohammedDehairy** [comment]
Thanks for reaching @DagAgren ,

Yes there is a way, you can use Swift Package Manager, unfortunately CocoaPods and Carthage are not yet compatible with M1 Macs as far as I know.

Mohamed

**Comment by DagAgren** [comment]
They are compatible, every other dependency we have works fine. That flag can be safely removed as long as you provide a properly built binary.

**Comment by mohammedDehairy** [comment]
Does the other dependencies provide pre-built framework? because if we provide a simulator build for ` x86_64 and arm64` then developers developing on normal Macs will face an issue, and won't be able to build on non-M1 Macs.

The only way to solve this is by distributing an `.XCFramework` rather than a `.framework`, but unfortunately the pod spec uses the `.framework` file not the XCFramework.

we'll fix this in the next release and make the podspec distribute the `.XCFramework`.

but for now the only way is through SPM.

**Comment by DagAgren** [comment]
Is there some reason to not just update the podspec to use the xcframework?

Like this? This seems to work fine when I tried forking and updating the Podfile to use the forked repo: https://github.com/Adyen/adyen-3ds2-ios/pull/22

**Comment by mohammedDehairy** [comment]
Thanks @DagAgren ,

We'll update the podspec file with the next release.

Mohamed

**Comment by DagAgren** [comment]
Any progress on this? macOS 12 is coming soon and is rumoured to disable the EXCLUDED_ARCHS hack so we need to fix this before that.

**Comment by DagAgren** [comment]
See, for instance, https://developer.apple.com/forums/thread/681749.

**Comment by descorp** [comment]
It is already on [develop](https://github.com/Adyen/adyen-3ds2-ios/blob/master/Adyen3DS2.podspec)
We are going to release this week.

Thanks for staying vigilant @DagAgren 
💚

**Comment by mohammedDehairy** [comment]
@DagAgren ,

the fix has been released.

Thanks for reporting the issue and for being patient! :-).

can you please try and let us know of any problems?

**Comment by mohammedDehairy** [comment]
Will close this issue due to lack of activity, please feel free to reopen if you still need our help regarding this issue.
