### ISSUE TITLE
Wrong ADY3DS2SDKVersion value

### ISSUE THREAD

**Issue by rokridi** [Adyen/adyen-3ds2-ios#25]
Hello.
It is mentioned in the documentation that the current SDK version is stored in `ADY3DS2SDKVersion`.
I suppose its value should be `2.2.3` if i am using the last SDK version, however i get `18` as a value.
There is also a [little mistake](https://github.com/Adyen/adyen-3ds2-ios#:~:text=let%20threeDS2SDKVersion%20%3D%20ADY3DS2SDKVersion()) inside the ReadMe: 
`ADY3DS2SDKVersion` is not a function => `()` should be omitted.
Thanks.

**Comment by mohammedDehairy** [comment]
Hi @rokridi ,

Thanks for reaching out!. :-)

You're right, the value should be `2.2.3` if you're using the latest version, and I did test it and it is indeed `2.2.3`, and it is indeed a function, and you should call it with `()`.

How can I reproduce the `18` value? can you share some code snippet? because I can't reproduce what you describe.

Mohamed

**Comment by rokridi** [comment]
Hi @mohammedDehairy 
Thanks for the reply.
Here, take a look at the screen shots.

<img width="1440" alt="Capture d’écran 2021-10-07 à 09 21 14" src="https://user-images.githubusercontent.com/896970/136338436-20c22af2-6205-46b2-becc-152568c36582.png">
<img width="1440" alt="Capture d’écran 2021-10-07 à 09 24 30" src="https://user-images.githubusercontent.com/896970/136338448-2c785176-c282-4772-9769-6dd234820730.png">
